### ISSUE TITLE
Buy Life Potion not working.

### ISSUE THREAD

**Issue by Ozakinn** [DanielJulian/epicRPGPlayer#1]
Unable to buy life potion when message.content or the epic rpg said that i need to buy in the shop. It skips it can go run rpg hunt without buying and dying which results in lost level.

**Comment by DanielJulian** [comment]
What do you mean by unable to buy life potion?
When your life gets below the configured hp_threshold, the bot doesnt execute rpg heal?

**Comment by Ozakinn** [comment]
> What do you mean by unable to buy life potion?
> When your life gets below the configured hp_threshold, the bot doesnt execute rpg heal?

It does. but when my life potion is 0, it doesnt buy on its own. I saw the script that buys 30 potion if empty but doesnt execute. Maybe the message.content or the feedback from epic rpg changed. I tried changing it but didnt fix. I just added a command that first do buy a potion then do rpg heal.

**Comment by DanielJulian** [comment]
> > What do you mean by unable to buy life potion?
> > When your life gets below the configured hp_threshold, the bot doesnt execute rpg heal?
> 
> It does. but when my life potion is 0, it doesnt buy on its own. I saw the script that buys 30 potion if empty but doesnt execute. Maybe the message.content or the feedback from epic rpg changed. I tried changing it but didnt fix. I just added a command that first do buy a potion then do rpg heal.

The RPG feedback didnt changed, its gotta be something off with your properties, probably one of the user name properties.
Mine are the following:
discord_user_name=Dano
discord_user_name_and_tag=Dano#9090
discord_user_id=181146325731286381

**Comment by Ozakinn** [comment]
> > > What do you mean by unable to buy life potion?
> > > When your life gets below the configured hp_threshold, the bot doesnt execute rpg heal?
> > 
> > 
> > It does. but when my life potion is 0, it doesnt buy on its own. I saw the script that buys 30 potion if empty but doesnt execute. Maybe the message.content or the feedback from epic rpg changed. I tried changing it but didnt fix. I just added a command that first do buy a potion then do rpg heal.
> 
> The RPG feedback didnt changed, its gotta be something off with your properties, probably one of the user name properties.
> Mine are the following:
> discord_user_name=Dano
> discord_user_name_and_tag=Dano#9090
> discord_user_id=181146325731286381

Heres mine.
# Discord user information
discord_user_name=Ozaki
discord_user_name_and_tag=Ozaki#5945
discord_user_id=873598299226128424

I also created my bot, which is in the same server. Also added the bot token to the config.

This is the line where It does not execute. It continues to hunts. I'll try recording it.
elif "you don't have a life potion to do this" in message.content:
                print("Sending buy a potion message")
                self.feedback_queue.put("Buy some potions bro!")
                self.feedback_queue.put("Drink a potion bro!")

**Comment by Ozakinn** [comment]
https://user-images.githubusercontent.com/21289418/128618877-8876170c-5da2-471a-8ce7-01acdd33c513.mp4

**Comment by DanielJulian** [comment]
I think your discord user ID is wrong in the configuration.
Your config says 873598299226128424
Discord is tagging you with a number that starts in 466748...
Double check that

**Comment by Ozakinn** [comment]
> I think your discord user ID is wrong in the configuration.
> Your config says 873598299226128424
> Discord is tagging you with a number that starts in 466748...
> Double check that

Oh right. Where can i find my Discord ID? I tried doing some chat and do Copy ID. but I think its dynamic or something. it changes value.

**Comment by DanielJulian** [comment]
![image](https://user-images.githubusercontent.com/21090149/128619155-a3a18d62-89d5-4ed2-985c-6b9190e4a78e.png)
Enter any voice chat, right click on you, and click on COPY ID.
ID is unique and never changes.
If you dont see the copy ID option, I think you have to enable some config on discord. you can google that

**Comment by Ozakinn** [comment]
Thanks!. It my discord ID all along. I guess i coped the wrong ID which is the ID for the specific message.
Looking forward for updates in the automation script.

**Comment by DanielJulian** [comment]
I stopped working on this a while ago haha, there are still many cool things to do and improve.
Maybe in the near future.
Cheers
